### ISSUE TITLE
panic: runtime error: db.marshalAttributeValues

### ISSUE THREAD

**Issue by tedder** [camptocamp/terraboard#96]
This is the same error as #90, but .. I can provide information and not close the ticket. The only thing I masked in the error was our s3 path. Note we're using terraform 12.24.

```
2020-06-29T12:17:48.896000 {"level":"info","msg":"Retrieving state from S3","path":"our/file","time":"2020-06-29T19:17:48Z","version_id":"0z7Dy7Qpm4SILXmTf5nxO4TJLeuL7RUt"}
2020-06-29T12:17:48.910000 panic: runtime error: invalid memory address or nil pointer dereference
2020-06-29T12:17:48.910000 [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xc8db68]
2020-06-29T12:17:48.910000 goroutine 25 [running]:
2020-06-29T12:17:48.910000 github.com/camptocamp/terraboard/db.marshalAttributeValues(0x0, 0xc00098ab70, 0xc000111610, 0x0)
2020-06-29T12:17:48.910000  /go/src/github.com/camptocamp/terraboard/db/db.go:82 +0x78
2020-06-29T12:17:48.910000 github.com/camptocamp/terraboard/db.(*Database).stateS3toDB(0xc00009f5c8, 0xc00098aa50, 0xc0002acc60, 0x14, 0xc000b2e840, 0x20, 0x0, 0x0, 0x0, 0x0, ...)
2020-06-29T12:17:48.910000  /go/src/github.com/camptocamp/terraboard/db/db.go:70 +0x23a
2020-06-29T12:17:48.910000 github.com/camptocamp/terraboard/db.(*Database).InsertState(0xc00009f5c8, 0xc0002acc60, 0x14, 0xc000b2e840, 0x20, 0xc00098aa50, 0x0, 0x0)
2020-06-29T12:17:48.910000  /go/src/github.com/camptocamp/terraboard/db/db.go:114 +0xa1
2020-06-29T12:17:48.910000 main.refreshDB(0x1, 0xc00009f5c8, 0x11f0220, 0xc0001c1130)
2020-06-29T12:17:48.910000  /go/src/github.com/camptocamp/terraboard/main.go:105 +0xb6b
2020-06-29T12:17:48.910000 created by main.main
2020-06-29T12:17:48.910000  /go/src/github.com/camptocamp/terraboard/main.go:164 +0x1c12
```

Pulling up that last-logged state file, it is linked to version v0.12.24. Here's the resources and types found in the 1100+ line file:
```
   1             "type": "AWS",
   1       "type": "aws_api_gateway_account",
   1       "type": "aws_api_gateway_deployment",
   1       "type": "aws_api_gateway_integration",
   1       "type": "aws_api_gateway_integration_response",
   1       "type": "aws_api_gateway_method",
   1       "type": "aws_api_gateway_method_response",
   1       "type": "aws_api_gateway_method_settings",
   1       "type": "aws_api_gateway_resource",
   1       "type": "aws_api_gateway_rest_api",
   1       "type": "aws_caller_identity",
   2       "type": "aws_cloudwatch_log_group",
   1       "type": "aws_iam_account_alias",
   2       "type": "aws_iam_group",
   2       "type": "aws_iam_group_membership",
   2       "type": "aws_iam_group_policy_attachment",
   6       "type": "aws_iam_policy",
   4       "type": "aws_iam_policy_document",
   2       "type": "aws_iam_role",
   5       "type": "aws_iam_role_policy_attachment",
   1       "type": "aws_iam_user",
   1       "type": "aws_kms_alias",
   1       "type": "aws_kms_key",
   1       "type": "aws_lambda_function",
   1       "type": "aws_lambda_permission",
   1       "type": "string"
```

It's been barfing for a few weeks; we were previously using a dockerhub build sha that supported Terraform 12.20 (and it was failing), but today to fix the panics we updated to terraboard v0.20.  It's still failing.

We deleted that one specific state file and things successfully starting up. I'm hoping these clues help to find the cause of the panic. I can provide specific snippets from the state file if you have suspicions about what caused it, but I don't want to have to scrub the entire state file.

Thanks.

**Comment by raphink** [comment]
So that error was linked to one specific state file, and removing it (and replacing with a newer version I guess) fixed it?

**Comment by tedder** [comment]
Yes, ultimately we removed the file and terraboard quit dying.

**Comment by raphink** [comment]
OK. And no other file caused this another time?

**Comment by tedder** [comment]
Correct. We've been running it for many months (perhaps a year?) and have hundreds of files, thousands of file versions and TF resources. (probably an undercount, but you get the idea.)

I believe some or all of the resources in that file were destroyed and the state was left behind, so that's another clue that might be helpful.
